export const SESSION_QUERY_KEY = "SESSION";
export const CATEGORIES_QUERY_KEY = "CATEGORIES";
export const FAVORITE_PRODUCT_QUERY_KEY = "FAVORITE-PRODUCTS";
export const BASE_PRODUCT_QUERY_KEY = "BASE_PRODUCT";
export const REVIEWS_QUERY_KEY = "REVIEWS";
export const CART_QUERY_KEY = "CART";
